language: ruby
cache:
  - bundler
  - yarn
rvm:
  - 2.7.0

env:
  - RAILS_ENV=test DB_USERNAME=postgres DB_DATABASE=evally_test DB_HOST=localhost DB_PASSWORD=''

sudo: required

addons:
  postgresql: "9.6"
  chrome: stable

script:
  - bundle exec rake

before_install:
  - gem install bundler:2.1.4
  - nvm install v11.4.0

before_script:
  - yarn install
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
