version: '3'
services:
  db:
    container_name: evally_db
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_webpacker
    command: ./bin/webpack-dev-server
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/webpacker.yml:/app/config/webpacker.yml
    ports:
      - '3035:3035'

  app:
    env_file:
      - ./docker/docker.env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_app
    command: bin/rails s -p 3000 -b '0.0.0.0'
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/webpacker.yml:/app/config/webpacker.yml
    ports:
      - '3000:3000'
    depends_on:
      - webpacker
      - db

volumes:
  postgres:

# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
