version: '3'
services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'

  app:
    build: .
    command: rails s
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - webpacker

volumes:
  postgres: