version: '3'
services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
    user: ${CURRENT_USER}

  app:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    user: ${CURRENT_USER}
    depends_on:
      - webpacker
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''

volumes:
  postgres:

# CURRENT_USER=$(id -u):$(id -g) need to be set in .bashrc / .zshrc to guarantee files creation as non-roor user

# # Useful commands

# docker-compose up -> start project
# docker-compose run app <command> -> run command like 'rails c' inside app container