version: '3'
services:
  db:
    container_name: evally_db
    image: postgres:10.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    image: evally_app:latest
    container_name: evally_webpacker
    command: ./bin/webpack-dev-server
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/webpacker.yml:/app/config/webpacker.yml
    ports:
      - '3035:3035'
  db_recruitable:
    container_name: evally_recruitable_db
    image: postgres:10.6-alpine
    volumes:
      - postgres_recruitable:/var/lib/postgresql/data
  evally_recruitable:
    image: evally_recruitable_app:latest
    container_name: evally_recruitable_app
    command: bin/rails s -p 3030 -b '0.0.0.0'
    depends_on:
      - db_recruitable
    environment:
      DATABASE_HOST: db_recruitable
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''
    ports:
      - '3030:3030'
  app:
    image: evally_app:latest
    env_file:
      - ./docker/docker.env
    container_name: evally_app
    user: ${CURRENT_USER}
    volumes:
      - .:/app
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/webpacker.yml:/app/config/webpacker.yml
    ports:
      - '3000:3000'
      - '1025:1025'
    depends_on:
      - webpacker
      - db

volumes:
  postgres:
  postgres_recruitable:

networks:
  default:
    external:
      name: evally_network

# docker network create evally_network --subnet 172.24.24.0/24
# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
