version: '3.8'
services:
  core_db:
    container_name: evally_core_db
    image: postgres:10.6-alpine
    environment:
       - RAILS_ENV=production
    volumes:
      - postgres:/var/lib/postgresql/data

  # webpacker:
  #   environment:
  #     - RAILS_ENV=development
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   container_name: evally_webpacker
    
  #   command: ./bin/webpack-dev-server
  #   # command: bundle exec rails assets:precompile

  #   volumes:
  #     - .:/app
  #     - ./config/database.example.yml:/app/config/database.yml
  #     - ./docker/env.example.yml:/app/config/env.yml
  #     - ./docker/webpacker.yml:/app/config/webpacker.yml
  #   ports:
  #     - '3035:3035'
  #   depends_on:
  #     - core_app

  redis:
    image: 'redis:7.0-alpine'
    command: redis-server 
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    
  sidekiq:
    depends_on:
      - 'redis'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/app

  core_app:
    environment:
      - RAILS_ENV=production
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: evally_core_app
    # command: ./bin/webpack
    init: true
    volumes:
      - .:/app
      - ./config/database.example.yml:/app/config/database.yml
      - ./docker/env.example.yml:/app/config/env.yml
      # - ./docker/webpacker.yml:/app/config/webpacker.yml
    ports:
      - '3000:3000'
      - '1025:1025'
    expose:
      - '3000'
    depends_on:
      - core_db
      - redis
      - sidekiq
      
volumes:
  postgres:
  postgres_recruitable:
  redis:

networks:
  default:
      name: evally_network

# docker network create evally_network --subnet 172.24.24.0/24
# CURRENT_USER=$(id -u):$(id -g) add to .bashrc / .zshrc to run container as non-root user
