default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch("DATABASE_HOST") || Rails.application.config.env.fetch(:database).fetch(:host) %>
  username: <%= ENV.fetch("DATABASE_USERNAME") || Rails.application.config.env.fetch(:database).fetch(:username) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") || Rails.application.config.env.fetch(:database).fetch(:password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: evally_development

test:
  <<: *default
  database: evally_test

cypress:
  <<: *default
  database: evally_cypress

# # PostgreSQL database for production purposes
production:
  adapter: postgresql
  encoding: utf8
  database: evally_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: evally_admin
  password: