default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: evally_development

test:
  <<: *default
  database: evally_test

cypress:
  <<: *default
  database: evally_cypress

# # PostgreSQL database for production purposes
production:
  adapter: postgresql
  encoding: utf8
  database: evally_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: evally_admin
  password: