default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['db_host'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  primary:
    <<: *default
    database: evally_development
  human_resources:
    <<: *default
    database: evally_human_resources_development
    migrations_paths: db/human_resources_migrate

test:
  primary:
    <<: *default
    database: evally_test
  human_resources:
    <<: *default
    database: evally_human_resources_test
