default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['db_host'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>

development:
  primary:
    <<: *default
    database: evally_development
  hr:
    <<: *default
    database: evally_hr_development
    migrations_paths: db/hr_migrate

test:
  primary:
    <<: *default
    database: evally_test
  hr:
    <<: *default
    database: evally_hr_test
